### Get all contacts (local)
GET http://localhost:3000/contacts

### Get single contact by id (local) - replace with a real id after seeding
GET http://localhost:3000/contacts/6a5644b84e74eaa3a73359c4

### Get all contacts (Render, once deployed) - replace with your Render URL
GET https://cse341-contacts-lwfl.onrender.com/contacts

### Get single contact by id (Render)
GET https://cse341-contacts-lwfl.onrender.com/contacts/6a5644b84e74eaa3a73359c4
